// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTW_u-SOEpvLiWSS6uaY7czERwPpblJ2o',
    appId: '1:662291047715:web:684c76aee3640ce480d896',
    messagingSenderId: '662291047715',
    projectId: 'shoe-store-app-e9350',
    authDomain: 'shoe-store-app-e9350.firebaseapp.com',
    storageBucket: 'shoe-store-app-e9350.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNx_zewz9DFBeeYxl6YCUaOhy1I5evDl8',
    appId: '1:662291047715:android:d3ee65da61254f9980d896',
    messagingSenderId: '662291047715',
    projectId: 'shoe-store-app-e9350',
    storageBucket: 'shoe-store-app-e9350.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTW_u-SOEpvLiWSS6uaY7czERwPpblJ2o',
    appId: '1:662291047715:web:f2e9bcb3bd790be480d896',
    messagingSenderId: '662291047715',
    projectId: 'shoe-store-app-e9350',
    authDomain: 'shoe-store-app-e9350.firebaseapp.com',
    storageBucket: 'shoe-store-app-e9350.firebasestorage.app',
  );
}
